<a href="https://colab.research.google.com/github/rohit25scs1003001308-lgtm/Rohit-Kumar_25scs1003001308_IILM-GN/blob/main/Movie_Recomendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re
import nltk
pd.set_option("display.max_columns", None)

In [ ]:
df = pd.read_csv("/content/imdb_top_1000.csv")
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"2,83,41,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"13,49,66,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"53,48,58,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"5,73,00,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"43,60,000"

In [ ]:
df['Overview'][0]

'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.'

# Data processing

In [ ]:
df['clean_overview'] = df['Overview'].str.lower()
df['clean_overview'] = df['clean_overview'].apply(lambda x: re.sub('[^a-zA-Z]', ' ', x))
df['clean_overview'] = df['clean_overview'].apply(lambda x: re.sub(r'\s+', ' ', x))
df['clean_overview']

0      two imprisoned men bond over a number of years...
1      an organized crime dynasty s aging patriarch t...
2      when the menace known as the joker wreaks havo...
3      the early life and career of vito corleone in ...
4      a jury holdout attempts to prevent a miscarria...
                             ...
995    a young new york socialite becomes interested ...
996    sprawling epic covering the life of a texas ca...
997    in hawaii in a private is cruelly punished for...
998    several survivors of a torpedoed merchant ship...
999    a man in london tries to help a counter espion...
Name: clean_overview, Length: 1000, dtype: object

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
# The tokenization was already performed and corrected in the previous step.
# This cell is no longer needed for tokenization.

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
import nltk
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
df['clean_overview'] = df['clean_overview'].apply(lambda x: [word for word in x.split() if word not in stop_words])
df['clean_overview']

0      [two, imprisoned, men, bond, number, years, fi...
1      [organized, crime, dynasty, aging, patriarch, ...
2      [menace, known, joker, wreaks, havoc, chaos, p...
3      [early, life, career, vito, corleone, new, yor...
4      [jury, holdout, attempts, prevent, miscarriage...
                             ...
995    [young, new, york, socialite, becomes, interes...
996    [sprawling, epic, covering, life, texas, cattl...
997    [hawaii, private, cruelly, punished, boxing, u...
998    [several, survivors, torpedoed, merchant, ship...
999    [man, london, tries, help, counter, espionage,...
Name: clean_overview, Length: 1000, dtype: object

In [ ]:
import nltk
# nltk.download('punkt_tab') # This is not a valid NLTK resource

In [ ]:
# The stop word removal was already done in the previous cell.
# This cell is no longer needed for stop word removal.

In [ ]:
# The clean_Overview column is already created and processed in the previous steps.
# This cell is no longer needed.

In [ ]:
display(df.head())

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,clean_overview
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"2,83,41,469","[two, imprisoned, men, bond, number, years, fi..."
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"13,49,66,411","[organized, crime, dynasty, aging, patriarch, ..."
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"53,48,58,444","[menace, known, joker, wreaks, havoc, chaos, p..."
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"5,73,00,000","[early, life, career, vito, corleone, new, yor..."
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"43,60,000","[jury, holdout, attempts, prevent, miscarriage..."

In [ ]:
display(df.head())

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,clean_overview
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"2,83,41,469","[two, imprisoned, men, bond, number, years, fi..."
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"13,49,66,411","[organized, crime, dynasty, aging, patriarch, ..."
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"53,48,58,444","[menace, known, joker, wreaks, havoc, chaos, p..."
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"5,73,00,000","[early, life, career, vito, corleone, new, yor..."
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"43,60,000","[jury, holdout, attempts, prevent, miscarriage..."

In [ ]:
df['Actors'] = df[['Star1', 'Star2', 'Star3', 'Star4']].agg(','.join, axis=1).apply(lambda x: x.split(',')[:4])
df['Director'] = df['Director'].apply(lambda x: x.split(','))

In [ ]:
df['Actors'][0]

['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler']

In [ ]:
def clean(sentence):
    temp = []
    for word in sentence:
        temp.append(word.lower().replace(' ', ''))
    return temp

In [ ]:
df['Genre'] = [clean(x) for x in df['Genre']]
df['Actors'] = [clean(x) for x in df['Actors']]
df['Director'] = [clean(x) for x in df['Director']]

In [ ]:
df['Actors'][0]

['timrobbins', 'morganfreeman', 'bobgunton', 'williamsadler']

In [ ]:
# combining all the columns data
columns = ['clean_overview', 'Genre', 'Actors', 'Director']
l = []
for i in range(len(df)):
    words = ''
    for col in columns:
        words += ' '.join(df[col][i]) + ' '
    l.append(words)
l

['two imprisoned men bond number years finding solace eventual redemption acts common decency d r a m a timrobbins morganfreeman bobgunton williamsadler frankdarabont ',
 'organized crime dynasty aging patriarch transfers control clandestine empire reluctant son c r i m e ,  d r a m a marlonbrando alpacino jamescaan dianekeaton francisfordcoppola ',
 'menace known joker wreaks havoc chaos people gotham batman must accept one greatest psychological physical tests ability fight injustice a c t i o n ,  c r i m e ,  d r a m a christianbale heathledger aaroneckhart michaelcaine christophernolan ',
 'early life career vito corleone new york city portrayed son michael expands tightens grip family crime syndicate c r i m e ,  d r a m a alpacino robertdeniro robertduvall dianekeaton francisfordcoppola ',
 'jury holdout attempts prevent miscarriage justice forcing colleagues reconsider evidence c r i m e ,  d r a m a henryfonda leej.cobb martinbalsam johnfiedler sidneylumet ',
 'gandalf aragorn lead world men sauron army draw gaze frodo sam approach mount doom one ring a c t i o n ,  a d v e n t u r e ,  d r a m a elijahwood viggomortensen ianmckellen orlandobloom peterjackson ',
 'lives two mob hitmen boxer gangster wife pair diner bandits intertwine four tales violence redemption c r i m e ,  d r a m a johntravolta umathurman samuell.jackson brucewillis quentintarantino ',
 'german occupied poland world war ii industrialist oskar schindler gradually becomes concerned jewish workforce witnessing persecution nazis b i o g r a p h y ,  d r a m a ,  h i s t o r y liamneeson ralphfiennes benkingsley carolinegoodall stevenspielberg ',
 'thief steals corporate secrets use dream sharing technology given inverse task planting idea mind c e a c t i o n ,  a d v e n t u r e ,  s c i - f i leonardodicaprio josephgordon-levitt elliotpage kenwatanabe christophernolan ',
 'insomniac office worker devil may care soapmaker form underground fight club evolves something much much d r a m a bradpitt edwardnorton meatloaf zachgrenier davidfincher ',
 'meek hobbit shire eight companions set journey destroy powerful one ring save middle earth dark lord sauron a c t i o n ,  a d v e n t u r e ,  d r a m a elijahwood ianmckellen orlandobloom seanbean peterjackson ',
 'presidencies kennedy johnson events vietnam watergate historical events unfold perspective alabama man iq whose desire reunited childhood sweetheart d r a m a ,  r o m a n c e tomhanks robinwright garysinise sallyfield robertzemeckis ',
 'bounty hunting scam joins two men uneasy alliance third race find fortune gold buried remote cemetery w e s t e r n clinteastwood eliwallach leevancleef aldogiuffrè sergioleone ',
 'frodo sam edge closer mordor help shifty gollum divided fellowship makes stand sauron new ally saruman hordes isengard a c t i o n ,  a d v e n t u r e ,  d r a m a elijahwood ianmckellen viggomortensen orlandobloom peterjackson ',
 'beautiful stranger leads computer hacker neo forbidding underworld discovers shocking truth life knows elaborate deception evil cyber intelligence a c t i o n ,  s c i - f i lillywachowski keanureeves laurencefishburne carrie-annemoss lanawachowski ',
 'story henry hill life mob covering relationship wife karen hill mob partners jimmy conway tommy devito italian american crime syndicate b i o g r a p h y ,  c r i m e ,  d r a m a robertdeniro rayliotta joepesci lorrainebracco martinscorsese ',
 'rebels brutally overpowered empire ice planet hoth luke skywalker begins jedi training yoda friends pursued darth vader bounty hunter named boba fett galaxy a c t i o n ,  a d v e n t u r e ,  f a n t a s y markhamill harrisonford carriefisher billydeewilliams irvinkershner ',
 'criminal pleads insanity admitted mental institution rebels oppressive nurse rallies scared patients d r a m a jacknicholson louisefletcher michaelberryman peterbrocco milosforman ',
 'real life one america foremost founding fathers first secretary treasury alexander hamilton captured live broadway richard rodgers theater original broadway cast b i o g r a p h y ,  d r a m a ,  h i s t o r y lin-manuelmiranda phillipasoo leslieodomjr. renéeelisegoldsberry thomaskail ',
 'greed class discrimination threaten newly formed symbiotic relationship wealthy park family destitute kim clan c o m e d y ,  d r a m a ,  t h r i l l e r kang-hosong leesun-kyun choyeo-jeong choiwoo-sik bongjoonho ',
 'nedumaaran rajangam maara sets make common man fly process takes world capital intensive industry several enemies stand way d r a m a suriya madhavan pareshrawal aparnabalamurali sudhakongara ',
 'team explorers travel wormhole space attempt ensure humanity survival a d v e n t u r e ,  d r a m a ,  s c i - f i matthewmcconaughey annehathaway jessicachastain mackenziefoy christophernolan ',
 'slums rio two kids paths diverge one struggles become photographer kingpin c r i m e ,  d r a m a kátialund alexandrerodrigues leandrofirmino matheusnachtergaele fernandomeirelles ',
 'family move suburbs sullen year old girl wanders world ruled gods witches spirits humans changed beasts a n i m a t i o n ,  a d v e n t u r e ,  f a m i l y daveighchase suzannepleshette miyuirino rumihiiragi hayaomiyazaki ',
 'following normandy landings group u soldiers go behind enemy lines retrieve paratrooper whose brothers killed action d r a m a ,  w a r tomhanks mattdamon tomsizemore edwardburns stevenspielberg ',
 'lives guards death row affected one charges black man accused child murder rape yet mysterious gift c r i m e ,  d r a m a ,  f a n t a s y tomhanks michaelclarkeduncan davidmorse bonniehunt frankdarabont ',
 'open minded jewish librarian son become victims holocaust uses perfect mixture humor imagination protect son dangers around camp c o m e d y ,  d r a m a ,  r o m a n c e robertobenigni nicolettabraschi giorgiocantarini giustinodurano robertobenigni ',
 'two detectives rookie veteran hunt serial killer uses seven deadly sins motives c r i m e ,  d r a m a ,  m y s t e r y morganfreeman bradpitt kevinspacey andrewkevinwalker davidfincher ',
 'young f b cadet must receive help incarcerated manipulative cannibal killer help catch another serial killer madman skins victims c r i m e ,  d r a m a ,  t h r i l l e r jodiefoster anthonyhopkins lawrencea.bonney kasilemmons jonathandemme ',
 'luke skywalker joins forces jedi knight cocky pilot wookiee two droids save galaxy empire world destroying battle station also attempting rescue princess leia mysterious darth vader a c t i o n ,  a d v e n t u r e ,  f a n t a s y markhamill harrisonford carriefisher alecguinness georgelucas ',
 'ronin requesting seppuku feudal lord palace told brutal suicide another ronin previously visited reveals pasts intertwined challenges clan integrity a c t i o n ,  d r a m a ,  m y s t e r y tatsuyanakadai akiraishihama shimaiwashita tetsurôtanba masakikobayashi ',
 'poor village attack bandits recruits seven unemployed samurai help defend a c t i o n ,  a d v e n t u r e ,  d r a m a toshirômifune takashishimura keikotsushima yukikoshimazaki akirakurosawa ',
 'angel sent heaven help desperately frustrated businessman showing life would like never existed d r a m a ,  f a m i l y ,  f a n t a s y jamesstewart donnareed lionelbarrymore thomasmitchell frankcapra ',
 'gotham city mentally troubled comedian arthur fleck disregarded mistreated society embarks downward spiral revolution bloody crime path brings face face alter ego joker c r i m e ,  d r a m a ,  t h r i l l e r joaquinphoenix robertdeniro zaziebeetz francesconroy toddphillips ',
 'promising young drummer enrolls cut throat music conservatory dreams greatness mentored instructor stop nothing realize student potential d r a m a ,  m u s i c milesteller j.k.simmons melissabenoist paulreiser damienchazelle ',
 'becomes quadriplegic paragliding accident aristocrat hires young man projects caregiver b i o g r a p h y ,  c o m e d y ,  d r a m a érictoledano françoiscluzet omarsy anneleny oliviernakache ',
 'tragic accident two stage magicians engage battle create ultimate illusion sacrificing everything outwit d r a m a ,  m y s t e r y ,  s c i - f i christianbale hughjackman scarlettjohansson michaelcaine christophernolan ',
 'undercover cop mole police attempt identify infiltrating irish gang south boston c r i m e ,  d r a m a ,  t h r i l l e r leonardodicaprio mattdamon jacknicholson markwahlberg martinscorsese ',
 'polish jewish musician struggles survive destruction warsaw ghetto world war ii b i o g r a p h y ,  d r a m a ,  m u s i c adrienbrody thomaskretschmann frankfinlay emiliafox romanpolanski ',
 'former roman general sets exact vengeance corrupt emperor murdered family sent slavery a c t i o n ,  a d v e n t u r e ,  d r a m a russellcrowe joaquinphoenix connienielsen oliverreed ridleyscott ',
 "former neo nazi skinhead tries prevent younger brother going wrong path d r a m a edwardnorton edwardfurlong beverlyd'angelo jenniferlien tonykaye ",
 'sole survivor tells twisty events leading horrific gun battle boat began five criminals met seemingly random police lineup c r i m e ,  m y s t e r y ,  t h r i l l e r kevinspacey gabrielbyrne chazzpalminteri stephenbaldwin bryansinger ',
 'mathilda year old girl reluctantly taken l professional assassin family murdered unusual relationship forms becomes prot g e learns assassin trade a c t i o n ,  c r i m e ,  d r a m a jeanreno garyoldman natalieportman dannyaiello lucbesson ',
 'lion prince simba father targeted bitter uncle wants ascend throne a n i m a t i o n ,  a d v e n t u r e ,  d r a m a robminkoff matthewbroderick jeremyirons jamesearljones rogerallers ',
 'cyborg identical one failed kill sarah connor must protect teenage son john connor advanced powerful cyborg a c t i o n ,  s c i - f i arnoldschwarzenegger lindahamilton edwardfurlong robertpatrick jamescameron ',
 'filmmaker recalls childhood falling love pictures cinema home village forms deep friendship cinema projectionist d r a m a ,  r o m a n c e philippenoiret enzocannavale antonellaattili isadanieli giuseppetornatore ',
 'young boy little sister struggle survive japan world war ii a n i m a t i o n ,  d r a m a ,  w a r tsutomutatsumi ayanoshiraishi akemiyamaguchi yoshikoshinohara isaotakahata ',
 'marty mcfly year old high school student accidentally sent thirty years past time traveling delorean invented close friend eccentric scientist doc brown a d v e n t u r e ,  c o m e d y ,  s c i - f i michaelj.fox christopherlloyd leathompson crispinglover robertzemeckis ',
 'mysterious stranger harmonica joins forces notorious desperado protect beautiful widow ruthless assassin working railroad w e s t e r n henryfonda charlesbronson claudiacardinale jasonrobards sergioleone ',
 'phoenix secretary embezzles employer client goes run checks remote motel run young man domination mother h o r r o r ,  m y s t e r y ,  t h r i l l e r anthonyperkins janetleigh veramiles johngavin alfredhitchcock ',
 'cynical expatriate american cafe owner struggles decide whether help former lover fugitive husband escape nazis french morocco d r a m a ,  r o m a n c e ,  w a r humphreybogart ingridbergman paulhenreid clauderains michaelcurtiz ',
 'tramp struggles live modern industrial society help young homeless woman c o m e d y ,  d r a m a ,  f a m i l y charleschaplin paulettegoddard henrybergman tinysandford charleschaplin ',
 'aid wealthy erratic tippler dewy eyed tramp fallen love sightless flower girl accumulates money able help medically c o m e d y ,  d r a m a ,  r o m a n c e charleschaplin virginiacherrill florencelee harrymyers charleschaplin ',
 'serving five year sentence violent crime year old boy sues parents neglect d r a m a zainalrafeea yordanosshiferaw boluwatifetreasurebankole kawsaralhaddad nadinelabaki ',
 'amid st ravages korean war sergeant leyman stumbles upon half frozen little girl parents help sight frantic scared verge death see full summary b i o g r a p h y ,  d r a m a ,  h i s t o r y erdemcan çetintekindor ismailhacioglu kyung-jinlee canulkay ',
 'vikram nonsense police officer accompanied simon partner hunt capture vedha smuggler murderer vedha tries change vikram life leads conflict a c t i o n ,  c r i m e ,  d r a m a pushkar madhavan vijaysethupathi shraddhasrinath gayatri ',
 'two strangers find linked bizarre way connection forms distance thing keep apart a n i m a t i o n ,  d r a m a ,  f a n t a s y ryûnosukekamiki monekamishiraishi ryônarita aoiyûki makotoshinkai ',
 'former wrestler mahavir singh phogat two wrestler daughters struggle towards glory commonwealth games face societal oppression a c t i o n ,  b i o g r a p h y ,  d r a m a aamirkhan sakshitanwar fatimasanashaikh sanyamalhotra niteshtiwari ',
 'teen miles morales becomes spider man universe must join five spider powered individuals dimensions stop threat realities a n i m a t i o n ,  a c t i o n ,  a d v e n t u r e peterramsey rodneyrothman shameikmoore jakejohnson bobpersichetti ',
 'devastating events avengers infinity war universe ruins help remaining allies avengers assemble order reverse thanos actions restore balance universe a c t i o n ,  a d v e n t u r e ,  d r a m a joerusso robertdowneyjr. chrisevans markruffalo anthonyrusso ',
 'avengers allies must willing sacrifice attempt defeat powerful thanos blitz devastation ruin puts end universe a c t i o n ,  a d v e n t u r e ,  s c i - f i joerusso robertdowneyjr. chrishemsworth markruffalo anthonyrusso ',
 'aspiring musician miguel confronted family ancestral ban music enters land dead find great great grandfather legendary singer a n i m a t i o n ,  a d v e n t u r e ,  f a m i l y adrianmolina anthonygonzalez gaelgarcíabernal benjaminbratt leeunkrich ',
 'help german bounty hunter freed slave sets rescue wife brutal mississippi plantation owner d r a m a ,  w e s t e r n jamiefoxx christophwaltz leonardodicaprio kerrywashington quentintarantino ',
 'eight years joker reign anarchy batman help enigmatic catwoman forced exile save gotham city brutal guerrilla terrorist bane a c t i o n ,  a d v e n t u r e christianbale tomhardy annehathaway garyoldman christophernolan ',
 'two friends searching long lost companion revisit college days recall memories friend inspired think differently even rest world called idiots c o m e d y ,  d r a m a aamirkhan madhavan monasingh sharmanjoshi rajkumarhirani ',
 'eight year old boy thought lazy trouble maker new art teacher patience compassion discover real problem behind struggles school d r a m a ,  f a m i l y amolegupte darsheelsafary aamirkhan tiscachopra aamirkhan ',
 'distant future small waste collecting robot inadvertently embarks space journey ultimately decide fate mankind a n i m a t i o n ,  a d v e n t u r e ,  f a m i l y benburtt elissaknight jeffgarlin fredwillard andrewstanton ',
 'east berlin agent secret police conducting surveillance writer lover finds becoming increasingly absorbed lives d r a m a ,  m y s t e r y ,  t h r i l l e r ulrichmühe martinagedeck sebastiankoch ulrichtukur florianhenckelvondonnersmarck ',
 'kidnapped imprisoned fifteen years oh dae su released find must find captor five days a c t i o n ,  d r a m a ,  m y s t e r y choimin-sik yooji-tae kanghye-jeong kimbyeong-ok chan-wookpark ',
 'man short term memory loss attempts track wife murderer m y s t e r y ,  t h r i l l e r guypearce carrie-annemoss joepantoliano markboonejunior christophernolan ',
 'journey find cure tatarigami curse ashitaka finds middle war forest gods tatara mining colony quest also meets san mononoke hime a n i m a t i o n ,  a c t i o n ,  a d v e n t u r e yôjimatsuda yurikoishida yûkotanaka billycrudup hayaomiyazaki ',
 'former prohibition era jewish gangster returns lower east side manhattan thirty years later must confront ghosts regrets old life c r i m e ,  d r a m a robertdeniro jameswoods elizabethmcgovern treatwilliams sergioleone ',
 'archaeologist adventurer indiana jones hired u government find ark covenant adolf hitler nazis obtain awesome powers a c t i o n ,  a d v e n t u r e harrisonford karenallen paulfreeman johnrhys-davies stevenspielberg ',
 'family heads isolated hotel winter sinister presence influences father violence psychic son sees horrific forebodings past future d r a m a ,  h o r r o r jacknicholson shelleyduvall dannylloyd scatmancrothers stanleykubrick ',
 'u army officer serving vietnam tasked assassinating renegade special forces colonel sees god d r a m a ,  m y s t e r y ,  w a r martinsheen marlonbrando robertduvall fredericforrest francisfordcoppola ',
 'space merchant vessel receives unknown transmission distress call one crew attacked mysterious life form soon realize life cycle merely begun h o r r o r ,  s c i - f i sigourneyweaver tomskerritt johnhurt veronicacartwright ridleyscott ',
 'story terminally ill man wishes live life fullest inevitable occurs told best friend d r a m a ,  m u s i c a l rajeshkhanna amitabhbachchan sumitasanyal rameshdeo hrishikeshmukherjee ',
 'executive shoe company becomes victim extortion chauffeur son kidnapped held ransom c r i m e ,  d r a m a ,  m y s t e r y toshirômifune yutakasada tatsuyanakadai kyôkokagawa akirakurosawa ',
 'insane general triggers path nuclear holocaust war room full politicians generals frantically tries stop c o m e d y petersellers georgec.scott sterlinghayden keenanwynn stanleykubrick ',
 'veteran british barrister must defend client murder trial surprise surprise c r i m e ,  d r a m a ,  m y s t e r y tyronepower marlenedietrich charleslaughton elsalanchester billywilder ',
 'refusing attack enemy position general accuses soldiers cowardice commanding officer must defend d r a m a ,  w a r kirkdouglas ralphmeeker adolphemenjou georgemacready stanleykubrick ',
 'wheelchair bound photographer spies neighbors apartment window becomes convinced one committed murder m y s t e r y ,  t h r i l l e r jamesstewart gracekelly wendellcorey thelmaritter alfredhitchcock ',
 'screenwriter develops dangerous relationship faded film star determined make triumphant return d r a m a ,  f i l m - n o i r williamholden gloriaswanson erichvonstroheim nancyolson billywilder ',
 'dictator adenoid hynkel tries expand empire poor jewish barber tries avoid persecution hynkel regime c o m e d y ,  d r a m a ,  w a r charleschaplin paulettegoddard jackoakie reginaldgardiner charleschaplin ',
 'april th regiment assembles wage war deep enemy territory two soldiers assigned race time deliver message stop men walking straight deadly trap d r a m a ,  t h r i l l e r ,  w a r dean-charleschapman georgemackay danielmays colinfirth sammendes ',
 'mythological story goddess created entire universe plot revolves around consequences humans build temple first born d r a m a ,  f a n t a s y ,  h o r r o r anandgandhi adeshprasad sohumshah jyotimalshe rahianilbarve ',
 'series mysterious events change life blind pianist must report crime technically know nothing c r i m e ,  d r a m a ,  m u s i c ayushmannkhurrana tabu radhikaapte anildhawan sriramraghavan ',
 'man goes extreme lengths save family punishment family commits accidental crime c r i m e ,  d r a m a ,  t h r i l l e r mohanlal meena ashasharath ansiba jeethujoseph ',
 'teacher lives lonely life struggling son custody life slowly gets better finds love receives good news son new luck brutally shattered innocent little lie d r a m a madsmikkelsen thomasbolarsen annikawedderkopp lassefogelstrøm thomasvinterberg ',
 'married couple faced difficult decision improve life child moving another country stay iran look deteriorating parent alzheimer disease d r a m a paymanmaadi leilahatami sarehbayat shahabhosseini asgharfarhadi ',
 'twins journey middle east discover family history fulfill mother last wishes d r a m a ,  m y s t e r y ,  w a r lubnaazabal mélissadésormeaux-poulin maximgaudette mustafakamel denisvilleneuve ',

In [ ]:
# combining all the columns data
columns = ['clean_overview', 'Genre', 'Actors', 'Director']
l = []
for i in range(len(df)):
    words = ''
    for col in columns:
        words += ' '.join(df[col][i]) + ' '
    l.append(words)
df['clean_input'] = l
df = df[['Series_Title', 'clean_input']]
df.head()

               Series_Title                                        clean_input
0  The Shawshank Redemption  two imprisoned men bond number years finding s...
1             The Godfather  organized crime dynasty aging patriarch transf...
2           The Dark Knight  menace known joker wreaks havoc chaos people g...
3    The Godfather: Part II  early life career vito corleone new york city ...
4              12 Angry Men  jury holdout attempts prevent miscarriage just...

# Feature Extraction

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
tfidf = TfidfVectorizer()
features = tfidf.fit_transform(df['clean_input'])

In [ ]:
# create cosine similarity matrix
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(features, features)
print(cosine_sim)

[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.01697667 0.01611054]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.01697667 ... 0.         1.         0.02921718]
 [0.         0.         0.01611054 ... 0.         0.02921718 1.        ]]

# Movie Recommendation

In [ ]:
index = pd.Series(df['Series_Title'])
index.head()

0    The Shawshank Redemption
1               The Godfather
2             The Dark Knight
3      The Godfather: Part II
4                12 Angry Men
Name: Series_Title, dtype: object

In [ ]:
def recommend_movies(title):
    movies = []
    if title not in index.values:
        print(f"Movie with title '{title}' not found in the dataset.")
        return movies
    idx = index[index == title].index[0]
    # print(idx)
    score = pd.Series(cosine_sim[idx]).sort_values(ascending=False)
    top10 = list(score.iloc[1:11].index)
    # print(top10)

    for i in top10:
        movies.append(df['Series_Title'][i])
    return movies

In [ ]:
recommend_movies('The Dark Knight Rises')

['Batman Begins',
 'The Dark Knight',
 'Interstellar',
 'Joker',
 'Dunkirk',
 'The Prestige',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Die Hard: With a Vengeance',
 'Yip Man',
 'The Incredibles']

In [ ]:
index[index == 'The Dark Knight Rises'].index[0]

np.int64(63)

In [ ]:
pd.Series(cosine_sim[3]).sort_values(ascending=False)

3      1.000000
974    0.345368
1      0.208278
720    0.123123
933    0.117130
         ...
238    0.000000
239    0.000000
240    0.000000
241    0.000000
480    0.000000
Length: 1000, dtype: float64

In [ ]:
recommend_movies('Interstellar')

['The Dark Knight Rises',
 'The Martian',
 'The Revenant',
 'Gattaca',
 'The Avengers',
 'The Gentlemen',
 'Hidden Figures',
 'Airplane!',
 'Aliens',
 'Dark Waters']

In [ ]:
recommend_movies('The Shawshank Redemption')

['Mystic River',
 'Dev.D',
 'Fa yeung nin wah',
 'Koe no katachi',
 'The Great Escape',
 'Hable con ella',
 'Se7en',
 'Short Cuts',
 'The Green Mile',
 'Casino Royale']

In [ ]:
len(df)

1000